from pydantic import BaseModel, Field, field_validator

class ValidateInput(BaseModel):
    ticket: str = Field(description='Tickets generated by a customer in the Customer Support System')

    @field_validator('ticket')
    @classmethod
    def validate_and_clean_ticket(cls, ticket):
        lines = [s.strip() for s in ticket.split('\n') if s.strip()]
        if len(lines) != 3:
            raise ValueError(
                "The ticket should be in the following format:\n"
                "ticket_id: id\n"
                "channel: email/chat/phone\n"
                "ticket_text: problem"
            )
        return lines[-1]